### ISSUE TITLE
XML self closing tags

### ISSUE THREAD

**Issue by directionless** [groob/plist#15]
Playing with https://github.com/kolide/launcher/ I'm getting reports that launchd seems to require self closing xml tags for booleans. 

I notice that this library used support this (https://github.com/groob/plist/commit/c271b43e16933e716ddf0901b77274302b1987fa), but that it was reverted in 4dc2eeab

The other plist library seems to have fixed this with a dedicated xml encoder -- https://github.com/DHowett/go-plist/issues/34

There's an underlying go xml issue for this as well -- https://github.com/golang/go/issues/21399

**Comment by groob** [comment]
I can repro with 
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>Label</key>
		<string>co.kolide.runload</string>
		<key>Program</key>
		<string>/Users/victor/run.sh</string>
		<key>RunAtLoad</key>
		<true></true>
	</dict>
</plist>
```

launchd on mojave rejects the plist. 

```
victor@kl ~> sudo launchctl load -w /Library/LaunchDaemons/co.kolide.runload.plist
/Library/LaunchDaemons/co.kolide.runload.plist: Invalid property list
```
