### ISSUE TITLE
Binary parsing truncates data

### ISSUE THREAD

**Issue by directionless** [groob/plist#22]
I noticed that when I'm parsing binary plists with a bunch of opaque data, it's often truncated. And this seems unique to binary parsing.

I don't have a test file I can share, but you can see this examining `/var/db/dslocal/nodes/Default/users/seph.plist` (or similar)

When read directly, it's the binary path and things like `LinkedIdentity` are truncated. But if it's converted to xml first, the data is correct. This happens when using both `plist.Unmarshal` and `plist.NewBinaryDecoder`

I've attached a trivial dump script -- [plist-dump.go.zip](https://github.com/groob/plist/files/4289210/plist-dump.go.zip)

**Comment by directionless** [comment]
print style debugging, I'm pretty sure the `bp.readCount` function is producing wrong data. I'm unsure how to fix it.

**Comment by groob** [comment]
Can you still reproduce with go1.14.1? I had the fuzzer tests start crashing on 1.14 and couldn't reproduce with 1.14.1.

**Comment by groob** [comment]
NVM I misread what you said(long day). I think the changes in #19 might help. 

I was able to reproduce the issue.

**Comment by groob** [comment]
This is now fixed from #19 and #26.

Thanks for filing.
